### ISSUE TITLE
firefly doesn't work after updating to the latest version of haven

### ISSUE THREAD

**Issue by Cathyhjj** [spc-group/haven#156]
firefly doesn't work after updating to the latest version of haven (**plan_window branch**), see errors below:

> Traceback (most recent call last):
>   File "/home/beams0/JUANJUAN.HUANG/mambaforge/envs/haven/bin/firefly", line 5, in <module>
>     from firefly.launcher import main
>   File "/home/beams0/JUANJUAN.HUANG/src/haven/src/firefly/__init__.py", line 1, in <module>
>     from . import display  # noqa: F401
>   File "/home/beams0/JUANJUAN.HUANG/src/haven/src/firefly/display.py", line 5, in <module>
>     from haven import registry
>   File "/home/beams0/JUANJUAN.HUANG/src/haven/src/haven/__init__.py", line 11, in <module>
>     from .instrument import (  # noqa: F401
>   File "/home/beams0/JUANJUAN.HUANG/src/haven/src/haven/instrument/__init__.py", line 1, in <module>
>     from .instrument_registry import InstrumentRegistry, registry  # noqa: F401
>   File "/home/beams0/JUANJUAN.HUANG/src/haven/src/haven/instrument/instrument_registry.py", line 11, in <module>
>     registry = InstrumentRegistry(auto_register=False, use_typhos=True)
> TypeError: __init__() got an unexpected keyword argument 'use_typhos'
> (haven) [juanjuan.huang@goldendale]~/src/haven/src/firefly/tests%

**Comment by Cathyhjj** [comment]
Solved by upgrading ophyd-registry from 0.5 to 0.8 `pip install --upgrade ophyd-registry`
and install blusky-adaptive package `mamba install bluesky-adaptive`
