### ISSUE TITLE
errors running firefly, branch planwindows

### ISSUE THREAD

**Issue by Cathyhjj** [spc-group/haven#191]
After pulling all the new changes from planwindows branch, I had the following error messages when running firefly:

> 
> Unable to import /home/beams/JUANJUAN.HUANG/.local/lib/python3.9/site-packages/PyQt5/Qt5/lib/libQt5Positioning.so.5: undefined symbol: _ZdlPvm, version Qt_5; typhos web views disabled.
> /home/beams0/JUANJUAN.HUANG/mambaforge/envs/haven/lib/python3.9/site-packages/apstools/devices/aps_data_management.py
> Traceback (most recent call last):
>   File "/home/beams0/JUANJUAN.HUANG/mambaforge/envs/haven/bin/firefly", line 5, in <module>
>     from firefly.launcher import main
>   File "/home/beams0/JUANJUAN.HUANG/src/haven/src/firefly/__init__.py", line 1, in <module>
>     from . import display  # noqa: F401
>   File "/home/beams0/JUANJUAN.HUANG/src/haven/src/firefly/display.py", line 10, in <module>
>     from haven import registry
>   File "/home/beams0/JUANJUAN.HUANG/src/haven/src/haven/__init__.py", line 12, in <module>
>     from .instrument import (  # noqa: F401
>   File "/home/beams0/JUANJUAN.HUANG/src/haven/src/haven/instrument/__init__.py", line 2, in <module>
>     from .ion_chamber import IonChamber  # noqa: F401
>   File "/home/beams0/JUANJUAN.HUANG/src/haven/src/haven/instrument/ion_chamber.py", line 15, in <module>
>     from apstools.devices.srs570_preamplifier import (
> ImportError: cannot import name 'calculate_settle_time' from 'apstools.devices.srs570_preamplifier' (/home/beams0/JUANJUAN.HUANG/mambaforge/envs/haven/lib/python3.9/site-packages/apstools/devices/srs570_preamplifier.py)

**Comment by Cathyhjj** [comment]
solved by reinstalling some packages
